project:
  type: website
  output-dir: docs
  
website:
  title: "KatherineVeronneauIntro"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - cats.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/KatherineVeronneau/KatherineVeronneauIntro
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Katherine Veronneau"

format:
  html:
    theme: morph
    toc: true

editor: source

